### ISSUE TITLE
Oboe Backend for Android

### ISSUE THREAD

**Issue by MineCake147E** [MineCake147E/MonoAudio#120]
## Background and motivation
Currently, audio output for Android relies on AudioTrack. Of course it's quite promising, but it'll be nice to have our own Oboe binding.

## Tasks
 - [ ] Gather information about ClangSharp and Oboe
 - [ ] Make some API candidates
 - [ ] Implement the API
