### ISSUE TITLE
Rename "MonoAudio" => "Shamisen"

### ISSUE THREAD

**Issue by MineCake147E** [MineCake147E/MonoAudio#53]
## Background

As the development of this library has progressed, .NET 5 has emerged and Mono is becoming a thing of the past.  
We are developing this library in the pursuit of performance. .NET 5 and .NET Core 3.1 were always beating Mono by a wide margin in recent benchmarks, so the current name "MonoAudio" no longer fits this library.  
**WE'LL NEVER SACRIFICE PERFORMANCE TO SOLVE THIS PROBLEM**, so we are renaming MonoAudio.  

## Tasks

- [x] Gather rename candidates
- [x] Decide new name of the library
- [x] Rename repository
- [x] Rename VS2019 Solution
- [x] Rename all VS2019 Projects
- [x] Rename all directories
- [x] Refactor all source codes
- [x] Refactor documentation and README.md
- [x] Change Logo and create NuGet Icon

## The rule of new name

- **Do not EXACTLY(but case INSENSITIVE) collide with other GitHub repositories with more than 100 stars**.
- Must be able to be C# identifier.
- Each word is not very long (<15 characters in total).
- Named after musical instruments(like [Oboe](https://github.com/google/oboe)).
  - Not to be a percussion instrument.
  - Optionally be a traditional Japanese musical instrument.

## Renaming Candidates

- [ ] Shakuhachi
- [ ] Shinobue
- [x] Shamisen
- [ ] Kokyu
- [ ] Kagurabue
