### ISSUE TITLE
CoreAudio API Wrapper for Windows 10

### ISSUE THREAD

**Issue by MineCake147E** [MineCake147E/MonoAudio#58]
## Background

Currently, output for Windows Desktop Apps relies NAudio and CSCore. They are all promising, but it'll be nice to have our own wrapper for Windows CoreAudio APIs.

## Tasks

- [ ] Gather information about COM Interoperation in .NET Core
- [ ] Define API Candidates
- [ ] Create a new `library` Project
- [ ] Implement new APIs
